import type { Metadata } from "next";
import "./globals.css";
import SiteConfig from "@crymson/web/SiteConfig";
import { config } from "../../lib/site.config";

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SiteConfig config={config}>
      <html lang="en">
        <body className="min-h-screen">{children}</body>
      </html>
    </SiteConfig>
  );
}
