import type { Metadata } from "next";
import "./globals.css";
import SiteConfig from "@crymson/web/SiteConfig";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
  return (
    <SiteConfig config={{}}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </SiteConfig>
  );
}
